TodoListApp/Controllers/AppRoleController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;

namespace TodoListApp.Controllers
{
    public class AppRoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;

        public AppRoleController(RoleManager<IdentityRole> roleManager)
        {
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            var roles = _roleManager.Roles;
            return View(roles);
        }

        [HttpGet]

        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]

        public async Task<IActionResult> Create(IdentityRole model)
        {
            //Avoid Duplicate Role
            if (!_roleManager.RoleExistsAsync(model.Name).GetAwaiter().GetResult())
            {
                _roleManager.CreateAsync(new IdentityRole(model.Name)).GetAwaiter().GetResult();
            }
            return RedirectToAction("Index");
        }

    }
}

TodoListApp/Controllers/TodoListModelsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using TodoListApp.Data;
using TodoListApp.Models;

namespace TodoListApp.Controllers
{
    public class TodoListModelsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<IdentityUser> _userManager;

        public TodoListModelsController(ApplicationDbContext context, UserManager<IdentityUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // GET: TodoListModels
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var UserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (UserId != null && User.IsInRole("User"))
            {

                var todo = from c in _context.TodoListModel
                           orderby c.Guid
                           where c.UserId == UserId
                           select c;
                return View(todo);
            }
            IQueryable<TodoListModel> items = from i in _context.TodoListModel orderby i.Guid select i;
            List<TodoListModel> todoList = await items.ToListAsync();
            return View(todoList);
        }

        // GET: TodoListModels/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var todoListModel = await _context.TodoListModel
                .FirstOrDefaultAsync(m => m.Guid == id);
            if (todoListModel == null)
            {
                return NotFound();
            }

            return View(todoListModel);
        }

        // GET: TodoListModels/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: TodoListModels/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        
        public async Task<IActionResult> Create([Bind("Guid,Title,Content,DateCreated, UserId")] TodoListModel todoListModel)
        {
            var user = User.FindFirstValue(ClaimTypes.NameIdentifier);

            if (ModelState.IsValid)
            {
                todoListModel.UserId = user;
                _context.Add(todoListModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(todoListModel);
        }

        // GET: TodoListModels/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var todoListModel = await _context.TodoListModel.FindAsync(id);
            if (todoListModel == null)
            {
                return NotFound();
            }
            return View(todoListModel);
        }

        // POST: TodoListModels/Edit/5
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, TodoListModel todoListModel)
        {

            var todo = await _context.TodoListModel.FindAsync(id);

            if (todo == null)
            {
               return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    todo.Content = todoListModel.Content != null ? todoListModel.Content : todo.Content;
                    todo.Title = todoListModel.Title != null ? todoListModel.Title : todo.Title;
                   
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TodoListModelExists(todoListModel.Guid))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(todoListModel);
        }

        // GET: TodoListModels/Delete/5
        [Authorize(Roles ="Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var todoListModel = await _context.TodoListModel
                .FirstOrDefaultAsync(m => m.Guid == id);
            if (todoListModel == null)
            {
                return NotFound();
            }

            return View(todoListModel);
        }

        // POST: TodoListModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var todoListModel = await _context.TodoListModel.FindAsync(id);
            _context.TodoListModel.Remove(todoListModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TodoListModelExists(int id)
        {
            return _context.TodoListModel.Any(e => e.Guid == id);
        }
    }
}

TodoListApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TodoListApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://fonts.googleapis.com/css?familly=Roboto&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="TodoListModels" asp-action="Index">TodoListApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TodoListModels" asp-action="Index">Home</a>
                        </li>
                       @if (User.Identity.IsAuthenticated){
                           if(User.IsInRole("Admin")){
                                        <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="AppRole" asp-action="Index">Role</a>
                                </li>
                           }
                       }
                       
                        
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TodoListApp by David
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>